name: CI
on:
  push:
    branches: [master, main]
  pull_request:
env:
  CARGO_TERM_COLOR: always
jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.0
      - name: Install rust
        uses: dtolnay/rust-toolchain@fa04a1451ff1842e2626ccb99004d0195b455a88 # master
        with:
          toolchain: stable
          components: rustfmt
      - name: cargo fmt -- --check
        run: cargo fmt --all -- --check
  check-unused-deps:
    name: Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0
      - uses: taiki-e/install-action@bffeee26d4db9be238a4ea78d8826604ebcb594d # v2.82.5
        with:
          tool: cargo-machete
      - run: cargo machete
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.0
      - name: Install rust
        id: install-rust
        uses: dtolnay/rust-toolchain@fa04a1451ff1842e2626ccb99004d0195b455a88 # master
        with:
          toolchain: stable
          components: clippy
      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          key: "${{ steps.install-rust.outputs.cachekey }}"
      - run: cargo clippy --frozen --all-targets -- -D warnings
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # bump this when bumping the MSRV
        rust: ["1.88.0", stable, beta]
    steps:
      - uses: actions/checkout@v7.0.0
      - name: Install rust
        id: install-rust
        uses: dtolnay/rust-toolchain@fa04a1451ff1842e2626ccb99004d0195b455a88 # master
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          key: "${{ steps.install-rust.outputs.cachekey }}"
      - uses: taiki-e/install-action@bffeee26d4db9be238a4ea78d8826604ebcb594d # v2.82.5
        with:
          tool: nextest@0.9.126
      - name: Test
        run: cargo nextest run
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0
      - name: Check
        uses: EmbarkStudios/cargo-deny-action@bb137d7af7e4fb67e5f82a49c4fce4fad40782fe # v2.0.20
